title: Jingwen Wang's Homepage
page-top-title: Jingwen Wang
top-section-bg-text: Business Information Systems
home-subtitle: Jingwen Wang&ensp;|&ensp;王敬文
copyright-text: '&copy; Jingwen Wang 2024-2025. All Rights Reserved.'
